/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

 
/**
 *
 * @author BRAYAN
 */
public class Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Cuenta
     */
    
    private String dato;
    public Cuenta() {
        initComponents();
    }
    
    
    public void setDato(String dato){
        this.dato = dato;
        jTxtNombre.setText(dato);
        System.out.println(dato);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jBRegistrarGastos = new javax.swing.JButton();
        jBRegistrarIngresos = new javax.swing.JButton();
        jBEditarUsuario = new javax.swing.JButton();
        jBListarRegistros = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtNombre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PANEL PRINCIPAL");

        jBRegistrarGastos.setBackground(new java.awt.Color(255, 0, 0));
        jBRegistrarGastos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRegistrarGastos.setForeground(new java.awt.Color(255, 255, 255));
        jBRegistrarGastos.setText("Registrar gastos");
        jBRegistrarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarGastosActionPerformed(evt);
            }
        });

        jBRegistrarIngresos.setBackground(new java.awt.Color(255, 0, 0));
        jBRegistrarIngresos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRegistrarIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jBRegistrarIngresos.setText("Registrar ingresos");
        jBRegistrarIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarIngresosActionPerformed(evt);
            }
        });

        jBEditarUsuario.setBackground(new java.awt.Color(255, 0, 0));
        jBEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jBEditarUsuario.setText("Editar usuario");
        jBEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarUsuarioActionPerformed(evt);
            }
        });

        jBListarRegistros.setBackground(new java.awt.Color(255, 0, 0));
        jBListarRegistros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBListarRegistros.setForeground(new java.awt.Color(255, 255, 255));
        jBListarRegistros.setText("Informacion Financiera");
        jBListarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarRegistrosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MENÚ");

        jTxtNombre.setEditable(false);
        jTxtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtNombre.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(jTxtNombre);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBRegistrarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jBRegistrarGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBListarRegistros)
                        .addGap(77, 77, 77)
                        .addComponent(jBEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBRegistrarIngresos)
                    .addComponent(jBRegistrarGastos))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBListarRegistros)
                    .addComponent(jBEditarUsuario))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarIngresosActionPerformed
        // TODO add your handling code here:
        
        Ingresos ingresos = new Ingresos();
        ingresos.setDato(jTxtNombre.getText());
        ingresos.setVisible(true);
    }//GEN-LAST:event_jBRegistrarIngresosActionPerformed

    private void jBRegistrarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarGastosActionPerformed
        // TODO add your handling code here:
        Gastos gastos = new Gastos();
        gastos.setDato(jTxtNombre.getText());
        gastos.setVisible(true);
    }//GEN-LAST:event_jBRegistrarGastosActionPerformed

    private void jBEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        usuario.setDato(jTxtNombre.getText());
        usuario.setVisible(true);
    }//GEN-LAST:event_jBEditarUsuarioActionPerformed

    private void jBListarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarRegistrosActionPerformed
        // TODO add your handling code here:
        Comparativa comparativa = new Comparativa();
        comparativa.setDato(jTxtNombre.getText());
        comparativa.setVisible(true);
    }//GEN-LAST:event_jBListarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditarUsuario;
    private javax.swing.JButton jBListarRegistros;
    private javax.swing.JButton jBRegistrarGastos;
    private javax.swing.JButton jBRegistrarIngresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
